### ISSUE TITLE
Can't load newsyslog plugin in td-agent

### ISSUE THREAD

**Issue by unikmhz** [athenahealth/fluent-plugin-newsyslog#2]
`td-agent` won't start when I reference newsyslog plugin in configuration.

Environment:
- CentOS 7
- td-agent 0.12.20 (bundled ruby 2.1.8p440)
- fluent-plugin-newsyslog 0.1.0 (installed via td-agent-gem)

Sample output:

```
[root@log ~]# td-agent-gem install fluent-plugin-newsyslog
Fetching: fluent-plugin-newsyslog-0.1.0.gem (100%)
Successfully installed fluent-plugin-newsyslog-0.1.0
Parsing documentation for fluent-plugin-newsyslog-0.1.0
Installing ri documentation for fluent-plugin-newsyslog-0.1.0
Done installing documentation for fluent-plugin-newsyslog after 0 seconds
1 gem installed
[root@log ~]# td-agent
2016-03-23 13:18:01 +0300 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-03-23 13:18:01 +0300 [info]: starting fluentd-0.12.20
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.1'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-mongo' version '0.7.12'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-newsyslog' version '0.1.0'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.4'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-s3' version '0.6.5'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-03-23 13:18:01 +0300 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-03-23 13:18:01 +0300 [info]: gem 'fluentd' version '0.12.20'
2016-03-23 13:18:01 +0300 [info]: adding source type="newsyslog"
2016-03-23 13:18:01 +0300 [error]: unexpected error error="uninitialized constant Fluent::TextParser::NewSyslogParser"
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-newsyslog-0.1.0/lib/fluent/plugin/in_newsyslog.rb:69:in `configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:150:in `add_source'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:91:in `block in configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `each'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:117:in `configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:91:in `run_configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:515:in `run_configure'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:146:in `block in start'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `call'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `main_process'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:325:in `block in supervise'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `fork'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `supervise'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:142:in `start'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/bin/fluentd:6:in `<top (required)>'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-03-23 13:18:01 +0300 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-03-23 13:18:01 +0300 [error]: /sbin/td-agent:7:in `load'
  2016-03-23 13:18:01 +0300 [error]: /sbin/td-agent:7:in `<main>'
2016-03-23 13:18:01 +0300 [info]: process finished code=256
2016-03-23 13:18:01 +0300 [warn]: process died within 1 second. exit.
```

Adding `require 'fluent/plugin/parser_newsyslog'` to `in_newsyslog.rb:initialize` seems to allow td-agent to load, but I didn't perform any further testing.

**Comment by scheuk** [comment]
I updated the newsyslog input plugin to include the parser plugin.
I'll push out 0.1.1 today with that fix.
